// Vue/src/components/List.vue
<script setup>
    import { ref, watch, toRaw } from "vue";
    import Item from "./Item.vue";
    import { debounce } from "../util.js";

    const list = ref([]);

    const saveListInLocalStorage = debounce((stuff) => {
        localStorage.setItem("list", JSON.stringify(stuff));
    }, 200);

    watch(list, (updatedList) => {
        saveListInLocalStorage(toRaw(updatedList));
    },{ deep: true });

    function init() {
        const savedList = localStorage.getItem("list");
        if (savedList) {
            list.value = JSON.parse(savedList);
        } else {
            list.value = [];
        }
    }

    init();

    function deleteItem(id) {
        list.value = list.value.filter((item) => item.id != id);
    }

    function addItem() {
        const item = {
            name: "",
            done: false,
            id: crypto.randomUUID(),
            new: true,
        };
        list.value.unshift(item);
    }

    function deleteList() {
        if (window.confirm("Do you really want to delete the whole list?")) {
            list.value = [];
        }
    }
</script>

<template>
    <menu>
        <button @click="addItem" aria-label="Add item">
            <i aria-hidden="true" class="fa-solid fa-plus"></i>
        </button>
        <button
            v-if="list.length > 0"
            @click="deleteList"
            aria-label="Delete list"
        >
            <i aria-hidden="true" class="fa-solid fa-trash-can"></i>
        </button>
    </menu>
    <ul v-if="list.length > 0">
        <template v-for="item in list" :key="item.id">
            <Item :item="item" @delete="deleteItem(item.id)"></Item>
        </template>
    </ul>
    <p v-else style="text-align: center">Add items</p>
</template>

<style scoped>
    .done {
        opacity: 0.3;
    }

    ul {
        list-style-type: none;
    }
    menu {
        margin: 20px 0px;
        display: flex;
        gap: 20px;
        justify-content: center;
    }
    button {
        background-color: var(--secondary-color);
        color: white;
        width: 40px;
        height: 40px;
        border-radius: 50%;
    }

    button:hover,
    button:focus-visible {
        background-color: var(--primary-color);
    }
</style>

// Svelte/src/components/List.svelte
<script>
    import Item from "./Item.svelte";
    import { debounce } from "../util.js";

    let list;

    function init() {
        const savedList = localStorage.getItem("list");
        if (savedList) {
            list = JSON.parse(savedList);
        } else {
            list = [];
            saveListInLocalStorage();
        }
    }

    function addItem() {
        const item = {
            name: "",
            done: false,
            id: crypto.randomUUID(),
            new: true,
        };
        list = [item, ...list];
        saveListInLocalStorage();
    }

    function deleteItem(id) {
        list = list.filter((item) => item.id != id);
        saveListInLocalStorage();
    }

    const saveListInLocalStorage = debounce(() => {
        localStorage.setItem("list", JSON.stringify(list));
    }, 200);

    function deleteList() {
        if (
            window.confirm(
                "Do you really want to delete the whole list?"
            )
        ) {
            list = [];
            saveListInLocalStorage();
        }
    }

    $: if (list) saveListInLocalStorage();

    init();
</script>

<menu>
    <button
        class="bigButton"
        on:click={addItem}
        aria-label="Add item"
    >
        <i aria-hidden="true" class="fa-solid fa-plus" />
    </button>
    {#if list.length > 0}
        <button
            class="bigButton"
            on:click={deleteList}
            aria-label="Delete list"
        >
            <i aria-hidden="true" class="fa-solid fa-trash-can" />
        </button>
    {/if}
</menu>

{#if list.length > 0}
    <ul>
        {#each list as item (item.id)}
            <Item
                bind:item
                on:delete={() => deleteItem(item.id)}
                on:save={saveListInLocalStorage}
            />
        {/each}
    </ul>
{:else}
    <p style="text-align:center">Add items</p>
{/if}

<style>
    ul {
        list-style-type: none;
    }
    menu {
        margin: 20px 0px;
        display: flex;
        gap: 20px;
        justify-content: center;
    }
    button {
        background-color: var(--secondary-color);
        color: white;
        width: 40px;
        height: 40px;
        border-radius: 50%;
    }

    button:hover,
    button:focus-visible {
        background-color: var(--primary-color);
    }
</style>
